sonar.projectKey=yvanvds_dartschool
sonar.organization=yvanvds

# Sources and tests
sonar.sources=lib
sonar.tests=test
sonar.sourceEncoding=UTF-8

# Exclusions
sonar.exclusions=bin/**,example/**,tool/**,smartschool/**,test/fixtures/**
sonar.test.exclusions=test/fixtures/**

# Coverage
sonar.dart.lcov.reportPaths=coverage/lcov.info
