name: Build
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  sonarqube:
    name: SonarQube
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      # The analysis requires to retrieve dependencies and build successfully
      - name: Setup Dart
        uses: dart-lang/setup-dart@v1
      - name: Build
        run: dart pub get
      - name: Analyze
        run: dart analyze
      - name: Test with coverage
        run: dart test --coverage=coverage
      - name: Convert coverage to lcov
        run: |
          dart pub global activate coverage
          dart pub global run coverage:format_coverage --lcov --in=coverage --out=coverage/lcov.info --report-on=lib
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v6
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}